#!/usr/bin/env bash

# Start with the simple dotfiles
dotfiles=( .bashrc .bash_aliases .bash_profile cool_prompt .vim .vimrc .inputrc .gitconfig )
for i in "${dotfiles[@]}"
do
    if [ ! -e ~/$i ]; then 
        echo "Creating ~/$i -> $(pwd)/$i"
        ln -s $(pwd)/$i $HOME/$i
    else
        echo "~/$i already exists; skipping."
    fi
done

# Create an env-specific file, just in case
if [ ! -f ~/.bashrc_local ]; then
  echo "Creating env-specific .bashrc file."
  echo "# Put environment-specific stuff here." > ~/.bashrc_local
fi

source ~/.bashrc
